### ISSUE TITLE
Can backbeat server sits directly on top of a Rails app?

### ISSUE THREAD

**Issue by marshallshen** [groupon/backbeat#10]
This service looks pretty slick! Great job!

If I have a Rails app and the app needs a workflow, is there a way to directly include Backbeat server as part of that Rails app? Or do I **have to** make Backbeat server as its own service?

**Comment by bauerjon** [comment]
@marshallshen it will have to be it's own service.

In the ruby client you can use the local context to run workflows inline, but I have only seen this useful for testing as it runs in a single process and there is no workflow history.

https://github.com/groupon/backbeat_ruby#testing.

**Comment by marshallshen** [comment]
Awesome, thanks!
